### ISSUE TITLE
Add Encoders

### ISSUE THREAD

**Issue by restouffer** [FRC2539/command-based#2]
Being able to control speed rather than power is important for precise movements, such as those we will do during the Autonomous period. To be able to accurately measure how far (and, by extension, how fast) of wheels are moving, we need to add encoders to the gear box.

Once those encoders are in place, and wired into the cRIO, we must add code to read the encoder values and add methods to the Talons that allow us to drive our motors at a set speed or for a set distance.

**Comment by FRC2539** [comment]
Encoders are now added. Creating new ticket for driving a set distance.
