### ISSUE TITLE
Add Gyro

### ISSUE THREAD

**Issue by restouffer** [FRC2539/command-based#3]
Knowing the direction we are facing on the field opens up many possibilities, particularly for executing exact turns and responding autonomously. Add the gyro to our robot (somewhere near the center) and wire it into the cRIO.

Our Gyro code should automatically detect the gyro's drift and compensate. It should store the drift value to file, so that in future runs the code will not need to recalculate the drift. Add a Command that can be run to re-calculate drift. Then add Commands to turn the robot to any given angle, both relative to the field and relative to the current orientation.

**Comment by FRC2539** [comment]
I believe this is now adequately addressed by the NaxX MXP.
